# Generated by Django 3.1.1 on 2020-10-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookCoins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercoin',
            name='coins',
            field=models.DecimalField(decimal_places=2, default='', max_digits=1000),
        ),
    ]
