# Generated by Django 3.1.1 on 2020-09-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='author',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
