# Generated by Django 3.1.1 on 2020-09-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200922_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='modalcode',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
