# Generated by Django 3.1.1 on 2020-10-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_userratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userratings',
            options={'verbose_name_plural': 'User Ratings'},
        ),
    ]
